TYPE_LIGHT_SENSOR = 0
TYPE_SOIL_SENSOR = 1
TYPE_HUMIAIR_SENSOR = 2
TYPE_TEMP_SENSOR = 3
TYPE_DIGITAL_OUTPUT = 4

MQTT_SERVER = "mqtt.ohstem.vn"
MQTT_PORT = 1883
MQTT_USERNAME = "nguyentruongthan"
MQTT_PASSWORD = ""

HEADER_CREATE = 0
HEADER_DELETE = 1
HEADER_SENSOR_VALUE = 2
HEADER_CONTROL_DEVICE = 3
HEADER_GET_DEVICE = 4
HEADER_CREATE_SCHEDULER = 5
HEADER_ACK = 6
HEADER_GET_SCHEDULER = 7
HEADER_DELETE_SCHEDULER = 8
HEADER_GET_LATEST_VALUE = 9
HEADER_LATEST_VALUE = 10
HEADER_GET_RULE = 11
HEADER_CREATE_RULE = 12
HEADER_GET_IS_AUTO = 13
HEADER_CREATE_IS_AUTO = 14
HEADER_DELETE_RULE = 15

FEED_NAME = None
COMPORT = None

CONDITION_LESS = '<'
CONDITION_EQUAL = '=='
CONDITION_GREATER = '>'
